spring.application.name=rate-limiter

spring.data.redis.host=month-believe-mice-20147.db.redis.io
spring.data.redis.port=15814
spring.data.redis.username=default
spring.data.redis.password=ZLQx1iFcJbgtzczmbAyLUuFwSGRXDPA4
